LibraryMvc/Models/AddAuthorDto.cs
using LibraryMvc.Models.Domain;

namespace LibraryMvc.Models
{
    public class AddAuthorDto
    {
        public string AuthorName { get; set; }

        public string AuthorEmail { get; set; }

        public virtual ICollection<Books>? Books { get; set; }
    }
}

LibraryMvc/Models/Domain/Author.cs
using System.ComponentModel.DataAnnotations;

namespace LibraryMvc.Models.Domain
{
    public class Author
    {
        [Key]
        public int AuthorId { get; set; }

        public string AuthorName { get; set; }

        public string AuthorEmail { get; set; }

        public virtual ICollection<Books> ?Books { get; set; }
    }
}

LibraryMvc/Models/Domain/Books.cs
using System.ComponentModel.DataAnnotations;

namespace LibraryMvc.Models.Domain
{
    public class Books
    {
        [Key]
        public int BookId { get; set; }

        public string BookTitle { get; set; }

        public int BookPrice { get; set; }

        public int BookPersonId { get; set; }

        public virtual Person ?Person { get; set; }

        public int BookAuthorId { get; set; }

        public virtual Author ?Author { get; set; }
    }
}

LibraryMvc/Models/Domain/Person.cs
using System.ComponentModel.DataAnnotations;

namespace LibraryMvc.Models.Domain
{
    public class Person
    {
        [Key]
        public int PersonId { get; set; }

        public string PersonName { get; set; }

        public string PhoneNumber { get; set; }

        public string Address { get; set; }

        public virtual ICollection<Books> ?Books { get; set; }
    }
}

LibraryMvc/Models/ErrorViewModel.cs
namespace LibraryMvc.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

LibraryMvc/Controllers/AuthorController.cs
using LibraryMvc.Data;
using LibraryMvc.Models;
using LibraryMvc.Models.Domain;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace LibraryMvc.Controllers
{
    public class AuthorController : Controller
    {
        private readonly LibraryDbContext _libraryDbContext;

        public AuthorController(LibraryDbContext libraryDbContext)
        {
            _libraryDbContext = libraryDbContext;
        }
        [HttpGet]
       
        public async Task<List<Author>> Index()
        {
            return await _libraryDbContext.Author.ToListAsync();
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddAuthorDto addAuthorDto)
        {
            if(addAuthorDto != null)
            {
                var author = new Author()
                {
                    AuthorName = addAuthorDto.AuthorName,
                    AuthorEmail = addAuthorDto.AuthorEmail,
                    Books = addAuthorDto.Books
                };
               await _libraryDbContext.Author.AddAsync(author);
               await _libraryDbContext.SaveChangesAsync();
               return RedirectToAction("Index");
            }
            return View();
        }
    }
}

LibraryMvc/Controllers/BookController.cs
using Microsoft.AspNetCore.Mvc;

namespace LibraryMvc.Controllers
{
    public class BookController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

LibraryMvc/Controllers/HomeController.cs
using LibraryMvc.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace LibraryMvc.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

LibraryMvc/Controllers/PersonController.cs
using Microsoft.AspNetCore.Mvc;

namespace LibraryMvc.Controllers
{
    public class PersonController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

LibraryMvc/Views/Author/Add.cshtml
@model LibraryMvc.Models.AddAuthorDto;


<p>@ViewBag.Success</p>
<div class="container">
    <div class="box p-5">
        <div class="row d-flex justify-content-center mt-5 border-dark border-2">
            <div class="col-6">
                <form action="AddStudent" method="post" enctype="multipart/form-data" class="bg-light p-3">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="title text-center mb-5  fw-bold "><h3>Add-Author</h3></div>
                    <div class="row mb-3 d-flex justify-content-between ">
                        <div class="col-3">
                            <label for="authorname" class="form-label">Author Name</label>
                        </div>
                        <div class="col-6 offset-3">
                            <input type="text" class="form-control" id="authorname" asp-for="AuthorName" asp-action="AddAuthor" asp-controller="Author" data-val="true" required maxlength="50">
                        </div>
                        @* <span asp-validation-for="Name" class="text-danger"></span> *@
                    </div>
                    <div class="row mb-3 d-flex justify-content-between">
                        <div class="col-3">
                            <label for="email" class="form-label">Email</label>
                        </div>
                        <div class="col-6 offset-3">
                            <input type="email" class="form-control" id="email" asp-for="AuthorEmail" asp-action="AddAuthor" asp-controller="Author" data-val="true" required maxlength="50">
                        </div>
                        @* <span asp-validation-for="Name" class="text-danger"></span> *@
                    </div>
                    <div class="mb-3">
                        <button type="submit" class="btn btn-primary">Submit</button>
                        <button type="reset" class="btn btn-primary">Reset</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

LibraryMvc/Views/Author/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div class="text-center m-4"><h3>Author List</h3></div>

@model List<LibraryMvc.Models.Domain.Author>

<table class="table">
    <thead>
        <tr>
            <th>
            <td>Id</td>
            <td>Name</td>
            <td>Email</td>
                @*  <td>Book Name</td> *@
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var x in Model)
        {
            <tr>
                <td>@x.AuthorId</td>
                <td>@x.AuthorName</td>
                <td>@x.AuthorEmail</td>
                @* <td>@x.Books</td> *@
            </tr>
        }
    </tbody>
</table>

LibraryMvc/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

LibraryMvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LibraryMvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LibraryMvc.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LibraryMvc</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - LibraryMvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>